### ISSUE TITLE
ERROR: Could not build wheels for tokenizers

### ISSUE THREAD

**Issue by kushagra-sharma10** [OpenNyAI/Opennyai#3]
Facing this error while installing opennyai in colab notebook. Any help is welcome. 
.
.
.
 error: subprocess-exited-with-error
  
  × Building wheel for tokenizers (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for tokenizers (pyproject.toml) ... error
  ERROR: Failed building wheel for tokenizers
  Building wheel for sacremoses (setup.py) ... done
  Created wheel for sacremoses: filename=sacremoses-0.0.53-py3-none-any.whl size=895259 sha256=dc5a1b43261a57bac24ace973af6b81d1d0382cf217f6adc2a7522af62ebd70c
  Stored in directory: /root/.cache/pip/wheels/00/24/97/a2ea5324f36bc626e1ea0267f33db6aa80d157ee977e9e42fb
Successfully built sacremoses
Failed to build tokenizers
ERROR: Could not build wheels for tokenizers, which is required to install pyproject.toml-based projects

**Comment by amant555** [comment]
Hi @kushagra-sharma10,
This is because colab has changed their default python version. While development we created everything to support python 3.7 and 3.8. I have created a card in our ToDo list to upgrade the requirements.  

Meanwhile I would suggest you to use the library on your local environment by following the steps given in readme.

Alternatively,
If you would still prefer to run on colab. You can install the library from source after making a minor change to requirements. 
Follow the steps below:

1. Remove the following line from notebook `!pip install opennyai`
2. Clone the repo using `!git clone https://github.com/OpenNyAI/Opennyai.git`
3.  Change the directory `cd Opennyai` 
4. Update the requirements in setup.py. (You can access the file by browsing in file explorer from left side in colab)
Change line number 37 with `transformers<4.18,>=4.1`
5. install the library by executing `!pip install .`

Here is a screenshot for reference. 
<img width="1789" alt="Screenshot 2023-05-19 at 17 27 36" src="https://github.com/OpenNyAI/Opennyai/assets/49357028/ab7d2e55-e14b-471c-933f-0121a7150fbe">


After this step library should get installed without any issues.  I am closing this issue. If you face any error feel free to re-open.
